apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
spec:
  type: LoadBalancer
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
