apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-namespace
spec:
  type: LoadBalancer
  selector:
    app: payment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
